Re-Former
Mhdez221993/re-former pull request #1
Opened 2021-06-02 16:02 UTC by ZeenatLawal

In this project we:

- Created a Re-former project where a user can create a form.
- Built the user model and added validations to the inputs.
- Used the form helper tags to build the form.

2021-06-02 17:42 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Great job on this project:clap::clap:.**

**Major highlights**

- The PR and commit messages are very descriptive and professional
- The project strictly follows the MVC pattern.

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**

- [ ] View

- Add the commented out form in the new.html.erb. Kindly leave it in the commented form. 

([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_with.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

- Also, add the commented out form_tag to the new.html.erb. Also leave them in the commented out form. Reason, already given above.

- [ ] Check my inline comments below and make the required changes.

**Optional**

- [ ] It will be nice to make the changes tag as optional in the inline comments below.

- [ ] form view to displays a list of the error messages (with #errors and full_messages usage) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_extra_shared_error.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-06-02 17:42 UTC, enaburekhan commented on README.md
> +- Run `rails console` to test the project
The detailed instructions for running the app are currently incomplete.  Let me add some instructions. Continuing from where you stopped:
Before `rails console`. First I need to test if the app is working as expected using 

- `rails server`
- `http://localhost:3000/users/new` to create a new user
- `http://localhost:3000/users/1/edit` to edit an existing user

To confirm this:

- Run `rails console`
- `User.all` to display the exiting user.

You can refactor the above instructions to produce something similar
Lastly, I couldn't run the app without running `yarn install`. So do well to include it in the instructions

2021-06-02 17:42 UTC, enaburekhan commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Remove commented codes. They make the codebase to be untidy, difficult to read and understand. Use git history if you must view previous codes.

2021-06-02 17:42 UTC, enaburekhan commented on app/views/users/edit.html.erb
> +  <% end %>
**Optional:**

- [ ] Kindly move the logic to a helper. There should be absolutely NO logic in views. 
Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) on how to use a helper in rails.

2021-06-02 17:42 UTC, enaburekhan commented on app/views/users/new.html.erb
> +    <% end %>
**Optional:**

- [ ] Kindly also move the logic to a helper. The reason, as already highlighted above.

2021-06-03 14:20 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: 
------------------
Hello @ZeenatLawal @Mhdez221993 great job working on the required changes :clap: your project is working really nice. :100: 
-----------------
Now you can merge this branch :smile: 
HAPPY CODING!!!! AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![200 (2)](https://user-images.githubusercontent.com/64173189/120660276-c7963280-c44c-11eb-8a4f-9ba589376718.gif)

2021-06-03 14:27 UTC, merged